// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpqvsedngdmzaeuorhxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwcXZzZWRuZ2RtemFldW9yaHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjc4NDIsImV4cCI6MjA1OTYwMzg0Mn0.nt406oPtuPc5AF3gUsAgn3AzrdvTv8Ba6M8EKwRhNos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);